name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build Forge/Forge.csproj --configuration Release --no-restore

      - name: Pack NuGet
        run: dotnet pack Forge/Forge.csproj --configuration Release --no-build --output ./artifacts

      - name: Publish NuGet Package
        if: success() && github.event_name == 'push'
        run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate

      - name: Rename DLLs for artifact upload
        run: |
          mv Forge/bin/Release/netstandard2.1/Gamesmiths.Forge.dll ./artifacts/Gamesmiths.Forge.netstandard2.1.dll
          mv Forge/bin/Release/netstandard2.1/Gamesmiths.Forge.pdb ./artifacts/Gamesmiths.Forge.netstandard2.1.pdb
          mv Forge/bin/Release/netstandard2.1/Gamesmiths.Forge.xml ./artifacts/Gamesmiths.Forge.netstandard2.1.xml
          mv Forge/bin/Release/net8.0/Gamesmiths.Forge.dll ./artifacts/Gamesmiths.Forge.net8.0.dll
          mv Forge/bin/Release/net8.0/Gamesmiths.Forge.pdb ./artifacts/Gamesmiths.Forge.net8.0.pdb
          mv Forge/bin/Release/net8.0/Gamesmiths.Forge.xml ./artifacts/Gamesmiths.Forge.net8.0.xml

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/*
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
